# Generated by Django 4.2.3 on 2023-07-25 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="用户ID"
            ),
        ),
        migrations.CreateModel(
            name="AuthRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("login_at", models.DateTimeField()),
                ("expires_by", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
