# Generated by Django 4.2.3 on 2023-07-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_id_authrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="motto",
            field=models.CharField(
                default="这个人很懒，什么都没有留下", max_length=256, verbose_name="个性签名"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="用户ID",
            ),
        ),
    ]
