# Generated by Django 4.2.3 on 2023-07-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_motto_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatar/default.png",
                upload_to="avatar/%Y%m%d/",
                verbose_name="头像",
            ),
        ),
    ]
