# Generated by Django 4.2.3 on 2023-07-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailCaptcha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                ("captcha", models.CharField(max_length=20, verbose_name="验证码")),
                (
                    "send_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
            ],
            options={
                "verbose_name": "邮箱验证码",
                "verbose_name_plural": "邮箱验证码",
                "ordering": ["-send_time"],
            },
        ),
    ]
